### ISSUE TITLE
Add labels to this repo that will be helpful for community contribution

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/community#4]
We chose to leave out PhET internal process labels for this repo. We want to investigate which labels might be most helpful for community contributors.

I'll look around at some open source projects and see what labels exist that might be helpful to import or amend GitHub defaults.

**Comment by BLFiedler** [comment]
A few pages with some interesting additions beyond the PhET labels:

- https://github.com/pixijs/pixijs/labels
- https://github.com/processing/p5.js/labels
- https://github.com/rails/rails/labels

**Comment by pixelzoom** [comment]
> We chose to leave out PhET internal process labels for this repo. We want to investigate which labels might be most helpful for community contributors.

I understand the motivation.  But this repo is causing problems that affect PhET internally.  And not having standard labels was never communicated to the team (a PSA would be great), which results in confusion and duplicate issues like #20, and makes it problematic to label things appropriately for internal processing.   So maybe if this repo is (by design) not going to conform to the standards of PhET's active repositories, then perhaps it should be removed from perennial/data/active-repos. That would also prevent problems like #19 and #21.

**Comment by BLFiedler** [comment]
Thanks for catching all this and taking some action and sorry for the extra work. We discussed this further and are going to continue to separate the labels here from the labels generally used for our internal processes. Errors like this should ideally be minimal in the future, as this will primarily be a documentation repository. @samreid felt we should keep community in active-repos for discoverability. Issues around linting will be addressed for consistency (#19, #21).

@samreid made a change in https://github.com/phetsims/phet-info/issues/210 to opt community out of a label related script along with a PSA to Slack.

Issue will continue for investigating appropriate labels in anticipation of Discussions use.
